insert into public.universities (name, short_code, email_domain)
values
  ('Princeton University', 'Princeton', 'princeton.edu'),
  ('Yale University', 'Yale', 'yale.edu'),
  ('University of Pennsylvania', 'UPenn', 'upenn.edu'),
  ('Dartmouth College', 'Dartmouth', 'dartmouth.edu'),
  ('Brown University', 'Brown', 'brown.edu'),
  ('California Institute of Technology', 'Caltech', 'caltech.edu'),
  ('Johns Hopkins University', 'JHU', 'jhu.edu'),
  ('University of Chicago', 'UChicago', 'uchicago.edu'),
  ('Duke University', 'Duke', 'duke.edu'),
  ('Northwestern University', 'Northwestern', 'northwestern.edu'),
  ('Carnegie Mellon University', 'CMU', 'cmu.edu'),

  ('University of Illinois Urbana-Champaign', 'UIUC', 'illinois.edu'),
  ('Georgia Institute of Technology', 'GeorgiaTech', 'gatech.edu'),
  ('Purdue University', 'Purdue', 'purdue.edu'),
  ('University of Wisconsin-Madison', 'Wisconsin', 'wisc.edu'),
  ('The Ohio State University', 'OSU', 'osu.edu'),
  ('Pennsylvania State University', 'PennState', 'psu.edu'),
  ('Texas A&M University', 'TAMU', 'tamu.edu'),
  ('University of Florida', 'UF', 'ufl.edu'),
  ('University of North Carolina at Chapel Hill', 'UNC', 'unc.edu'),
  ('University of Virginia', 'UVA', 'virginia.edu'),
  ('University of California, San Diego', 'UCSD', 'ucsd.edu'),
  ('University of California, Irvine', 'UCI', 'uci.edu'),
  ('University of California, Santa Barbara', 'UCSB', 'ucsb.edu'),
  ('University of California, Davis', 'UCDavis', 'ucdavis.edu'),
  ('University of California, Santa Cruz', 'UCSC', 'ucsc.edu'),
  ('University of Maryland, College Park', 'UMD', 'umd.edu'),

  ('University of Toronto', 'UofT', 'utoronto.ca'),
  ('University of British Columbia', 'UBC', 'ubc.ca'),
  ('McGill University', 'McGill', 'mcgill.ca'),
  ('University of Waterloo', 'Waterloo', 'uwaterloo.ca'),
  ('University of Alberta', 'UAlberta', 'ualberta.ca'),
  ('University of Calgary', 'UCalgary', 'ucalgary.ca'),
  ('Western University', 'Western', 'uwo.ca'),
  ('Queen''s University', 'Queens', 'queensu.ca'),
  ('Simon Fraser University', 'SFU', 'sfu.ca'),
  ('University of Ottawa', 'uOttawa', 'uottawa.ca'),
  ('York University', 'YorkU', 'yorku.ca'),
  ('Toronto Metropolitan University', 'TMU', 'torontomu.ca'),
  ('University of Manitoba', 'Manitoba', 'umanitoba.ca'),
  ('Dalhousie University', 'Dal', 'dal.ca')
on conflict (email_domain) do update
set name = excluded.name,
    short_code = excluded.short_code,
    updated_at = now();